openapi: 3.0.1
info:
  title: KAKAO
  description: This is API for Kakao
  version: '1.0'
servers:
  - url: https://kapi.kakao.com
paths:
  /access-token:
    get:
      summary: Access Token
      operationId: access-token
      responses:
        '200':
          description: The OK response
          content:
            text/html:
              schema:
                type: string
  /profile:
    get:
      summary: Profile
      operationId: profile
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The OK response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/profileResponse'
components:
  schemas:
    profileResponse:
      type: object
      properties:
        nickName:
          type: string
        profileImageURL:
          type: string
        thumbnailURL:
          type: string
